package com.gpdev.rdp.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gpdev.rdp.model.Categoria;
import com.gpdev.rdp.model.Receta;
import com.gpdev.rdp.model.Plato;

import com.gpdev.rdp.dao.CategoriaDao;
import com.gpdev.rdp.dao.RecetaDao;
import com.gpdev.rdp.dao.PlatoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoriaDaoConfig;
    private final DaoConfig recetaDaoConfig;
    private final DaoConfig platoDaoConfig;

    private final CategoriaDao categoriaDao;
    private final RecetaDao recetaDao;
    private final PlatoDao platoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoriaDaoConfig = daoConfigMap.get(CategoriaDao.class).clone();
        categoriaDaoConfig.initIdentityScope(type);

        recetaDaoConfig = daoConfigMap.get(RecetaDao.class).clone();
        recetaDaoConfig.initIdentityScope(type);

        platoDaoConfig = daoConfigMap.get(PlatoDao.class).clone();
        platoDaoConfig.initIdentityScope(type);

        categoriaDao = new CategoriaDao(categoriaDaoConfig, this);
        recetaDao = new RecetaDao(recetaDaoConfig, this);
        platoDao = new PlatoDao(platoDaoConfig, this);

        registerDao(Categoria.class, categoriaDao);
        registerDao(Receta.class, recetaDao);
        registerDao(Plato.class, platoDao);
    }
    
    public void clear() {
        categoriaDaoConfig.clearIdentityScope();
        recetaDaoConfig.clearIdentityScope();
        platoDaoConfig.clearIdentityScope();
    }

    public CategoriaDao getCategoriaDao() {
        return categoriaDao;
    }

    public RecetaDao getRecetaDao() {
        return recetaDao;
    }

    public PlatoDao getPlatoDao() {
        return platoDao;
    }

}
