package com.gpdev.rdp.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.gpdev.rdp.model.Categoria;

import com.gpdev.rdp.model.Receta;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECETAS".
*/
public class RecetaDao extends AbstractDao<Receta, Long> {

    public static final String TABLENAME = "RECETAS";

    /**
     * Properties of entity Receta.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Nombre = new Property(1, String.class, "nombre", false, "NOMBRE");
        public final static Property Ingredientes = new Property(2, String.class, "ingredientes", false, "INGREDIENTES");
        public final static Property Preparacion = new Property(3, String.class, "preparacion", false, "PREPARACION");
        public final static Property IdCategoria = new Property(4, Long.class, "idCategoria", false, "ID_CATEGORIA");
    }

    private DaoSession daoSession;

    private Query<Receta> categoria_RecetasQuery;

    public RecetaDao(DaoConfig config) {
        super(config);
    }
    
    public RecetaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Receta entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(2, nombre);
        }
 
        String ingredientes = entity.getIngredientes();
        if (ingredientes != null) {
            stmt.bindString(3, ingredientes);
        }
 
        String preparacion = entity.getPreparacion();
        if (preparacion != null) {
            stmt.bindString(4, preparacion);
        }
 
        Long idCategoria = entity.getIdCategoria();
        if (idCategoria != null) {
            stmt.bindLong(5, idCategoria);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Receta entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(2, nombre);
        }
 
        String ingredientes = entity.getIngredientes();
        if (ingredientes != null) {
            stmt.bindString(3, ingredientes);
        }
 
        String preparacion = entity.getPreparacion();
        if (preparacion != null) {
            stmt.bindString(4, preparacion);
        }
 
        Long idCategoria = entity.getIdCategoria();
        if (idCategoria != null) {
            stmt.bindLong(5, idCategoria);
        }
    }

    @Override
    protected final void attachEntity(Receta entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Receta readEntity(Cursor cursor, int offset) {
        Receta entity = new Receta( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nombre
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ingredientes
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // preparacion
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // idCategoria
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Receta entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombre(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIngredientes(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPreparacion(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIdCategoria(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Receta entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Receta entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Receta entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "recetas" to-many relationship of Categoria. */
    public List<Receta> _queryCategoria_Recetas(Long idCategoria) {
        synchronized (this) {
            if (categoria_RecetasQuery == null) {
                QueryBuilder<Receta> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdCategoria.eq(null));
                queryBuilder.orderRaw("T.'NOMBRE' ASC");
                categoria_RecetasQuery = queryBuilder.build();
            }
        }
        Query<Receta> query = categoria_RecetasQuery.forCurrentThread();
        query.setParameter(0, idCategoria);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCategoriaDao().getAllColumns());
            builder.append(" FROM RECETAS T");
            builder.append(" LEFT JOIN CATEGORIAS T0 ON T.\"ID_CATEGORIA\"=T0.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Receta loadCurrentDeep(Cursor cursor, boolean lock) {
        Receta entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Categoria categoria = loadCurrentOther(daoSession.getCategoriaDao(), cursor, offset);
        entity.setCategoria(categoria);

        return entity;    
    }

    public Receta loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Receta> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Receta> list = new ArrayList<Receta>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Receta> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Receta> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
